step 4 -> step 5
niyazz/DotNext-Moscow-2020 pull request #5
Opened 2021-02-20 16:04 UTC by niyazz

2021-02-26 17:45 UTC, max-arshinov requested changes

2021-02-26 17:45 UTC, max-arshinov commented on Apps/HightechAngular.Web/Data/ApplicationDbContext.cs
> +        public virtual DbSet<Product> Products { get; set; } = default!;
https://docs.microsoft.com/en-us/ef/core/miscellaneous/nullable-reference-types#dbcontext-and-dbset

2021-02-26 17:45 UTC, max-arshinov commented on HightechAngular.Account/Features/Account/Complete/CompleteOrderContext.cs
> +        public Order Order { get; }
можно использовать базовый класс

2021-02-26 17:45 UTC, max-arshinov commented on HightechAngular.Account/Features/Account/Pay/PayOrderContext.cs
> +        public Order Order { get; }
можно вынести в базовый класс

2021-02-26 17:45 UTC, max-arshinov commented on HightechAngular.Shop/Features/Cart/Remove/RemoveCartItemContext.cs
> +        public Product Product { get; }
тоже можно базовый класс сделать

2021-02-26 17:45 UTC, max-arshinov commented on IdentityMvcMetanit/Controllers/AccountController.cs
> +                    await Authenticate(model.Email); // аутентификация
// это бесполезный комментарий. Он ничего не объясняет, если его убрать код станет чище, понятность не пострадает

2021-02-26 17:45 UTC, max-arshinov commented on IdentityMvcMetanit/Controllers/AccountController.cs
> +            // создаем один claim
// ну да, без этого коммента я бы не понял

2021-02-26 17:45 UTC, max-arshinov commented on IdentityMvcMetanit/Controllers/AccountController.cs
> +                new Claim(ClaimsIdentity.DefaultNameClaimType, userName)
// 1 клейм

2021-02-26 17:45 UTC, max-arshinov commented on IdentityMvcMetanit/Controllers/AccountController.cs
> +            // создаем объект ClaimsIdentity
cmon)

2021-02-26 17:45 UTC, max-arshinov commented on IdentityMvcMetanit/Controllers/AccountController.cs
> +                    // добавляем пользователя в бд
// прекратите это)

2021-02-26 17:45 UTC, max-arshinov commented on IdentityMvcMetanit/Controllers/AccountController.cs
> +                    await Authenticate(model.Email); // аутентификация
// а это снова бесполезный комментарий

2021-02-26 17:45 UTC, max-arshinov commented on IdentityMvcMetanit/Startup.cs
> +            /* services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
а почему закомментирован?

2021-02-26 18:02 UTC, niyazz commented on IdentityMvcMetanit/Startup.cs
> +            /* services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
тут использовался подход аутентификации с куками, начал делать с токенами, поэтому хотел проиллюстрировать, что с куками тоже проделал работу

2021-03-01 15:19 UTC, niyazz commented on IdentityMvcMetanit/Controllers/AccountController.cs
> +                    await Authenticate(model.Email); // аутентификация
Исправил

2021-03-01 15:19 UTC, niyazz commented on IdentityMvcMetanit/Controllers/AccountController.cs
> +                    // добавляем пользователя в бд
Исправил

2021-03-01 15:19 UTC, niyazz commented on IdentityMvcMetanit/Controllers/AccountController.cs
> +            // создаем объект ClaimsIdentity
Исправил

2021-03-01 15:19 UTC, niyazz commented on IdentityMvcMetanit/Controllers/AccountController.cs
> +                new Claim(ClaimsIdentity.DefaultNameClaimType, userName)
Исправил

2021-03-01 15:19 UTC, niyazz commented on IdentityMvcMetanit/Controllers/AccountController.cs
> +                    await Authenticate(model.Email); // аутентификация
Исправил

2021-03-01 15:19 UTC, niyazz commented on HightechAngular.Shop/Features/Cart/Remove/RemoveCartItemContext.cs
> +        public Product Product { get; }
Исправил

2021-03-01 15:19 UTC, niyazz commented on HightechAngular.Account/Features/Account/Pay/PayOrderContext.cs
> +        public Order Order { get; }
Исправил

2021-03-01 15:19 UTC, niyazz commented on HightechAngular.Account/Features/Account/Complete/CompleteOrderContext.cs
> +        public Order Order { get; }
Исправил

2021-03-01 15:19 UTC, niyazz commented on Apps/HightechAngular.Web/Data/ApplicationDbContext.cs
> +        public virtual DbSet<Product> Products { get; set; } = default!;
Исправил

2021-03-07 09:46 UTC, max-arshinov requested changes

2021-03-07 09:46 UTC, max-arshinov commented on HightechAngular.Account/Features/Account/Complete/CompleteOrderCommandHandler.cs
> +            var shipState = new Order.OrderStates.Shipped(input.Order);
Здесь либо вызвать (Order.GetState() is Order.New newState) и разобрать оба варианта, возвращать соответствующий HandlerResult, либо поменять сигнатуру метода на Task<OrderStatus>. Сейчас сигнатура предполагает, что вы не выбрасываете Exception'ы для валидации, а вы выбрасываете

2021-03-07 09:46 UTC, max-arshinov commented on HightechAngular.Account/Features/Account/Dispute/DisputeOrderCommandHandler.cs
> +            var shipState = new Order.OrderStates.Shipped(input.Order);
Аналогично

2021-03-07 09:46 UTC, max-arshinov commented on HightechAngular.Admin/Features/Admin/Complete/CompleteOrderAdminCommandHandler.cs
> +            var shipState = new Order.OrderStates.Shipped(input.Order);
аналогично

2021-03-07 09:46 UTC, max-arshinov commented on HightechAngular.Admin/Features/Admin/Complete/CompleteOrderAdminCommandHandler.cs
> +            return new HandlerResult<OrderStatus>(input.Order.Status);
Здесь можно просто input.Order.Status возвращать через implicit

2021-03-07 09:46 UTC, max-arshinov commented on HightechAngular.Core/Base/BaseOrderContext.cs
> +    public class BaseOrderContext<T> :
Лучше придерживаться одного стиля наименования переменных. В данном случае это OrderContextBase. Так по-умолчнаию именует rider/resharper при рефакторинге

2021-03-07 09:46 UTC, max-arshinov commented on HightechAngular.Core/Entities/OrderStates.cs
> +                public New(Order order) :base(order){}
Не хватает проверки на то, что order в правильном сосотоянии

2021-03-21 08:05 UTC, max-arshinov approved these changes

2021-03-21 08:06 UTC, merged