Реализация 6-го шага после рефакторинга из примера с правильной реализацией
niyazz/DotNext-Moscow-2020 pull request #6
Opened 2021-03-07 09:53 UTC by niyazz

2021-03-07 10:16 UTC, max-arshinov requested changes

2021-03-07 10:16 UTC, max-arshinov commented on HightechAngular.Account/Features/Account/Complete/CompleteOrderCommandHandler.cs
> +            return new HandlerResult<OrderStatus>(result!.EligibleStatus);
не-не-не. Если `result == null``, то нужно возвращать другой результат с ошибкой валидации, а нес успех с null'ом

2021-03-07 10:16 UTC, max-arshinov commented on HightechAngular.Account/Features/Account/Dispute/DisputeOrderCommandHandler.cs
>              return new HandlerResult<OrderStatus>(input.Order.Status);
аналогичо

2021-03-07 10:16 UTC, max-arshinov commented on HightechAngular.Account/Features/Account/Pay/PayOrderCommandHandler.cs
> +                ((Order.New newOrder) => newOrder.BecomePaid());
аналогично

2021-03-12 17:08 UTC, niyazz commented on HightechAngular.Account/Features/Account/Complete/CompleteOrderCommandHandler.cs
> +            return new HandlerResult<OrderStatus>(result!.EligibleStatus);
исправил

2021-03-12 17:08 UTC, niyazz commented on HightechAngular.Account/Features/Account/Dispute/DisputeOrderCommandHandler.cs
>              return new HandlerResult<OrderStatus>(input.Order.Status);
исправил

2021-03-12 17:09 UTC, niyazz commented on HightechAngular.Account/Features/Account/Pay/PayOrderCommandHandler.cs
> +                ((Order.New newOrder) => newOrder.BecomePaid());
исправил

2021-03-14 10:34 UTC, niyazz commented on HightechAngular.Core/Base/BaseOrderContext.cs
> +        // через public TState State { get; }, пока не выйдет, поскольку IHasOrderState<TState> появляется на 7-ом шаге
На 7 шаге у меня все интерфейсы есть, просто не хочу плодить конфликты когда буду сливать 6 в 7. После этого заменю на дженерик стейт.

2021-03-21 08:25 UTC, merged